server:
  port: 8095

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb?createDatabaseIfNotExist=true
    username: postgres
    password: user24
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 6D7662M7gmjq6qo736C35616B70sI5zyWiPKmrOsJuctP766B37396F746A71647F
  expiration: 86400000 # 24 hours